version: '3.3'

services:

    typescript-stack:
        container_name: ${IMAGE_NAME}-${CONTAINER_ID}
        image: ${IMAGE_NAME}:${IMAGE_TAG}

        build:
            context: ../../
            dockerfile: ./configs/docker/Dockerfile
            args:
              NODE_VERSION: ${NODE_VERSION}
              DEBIAN_VERSION: ${DEBIAN_VERSION}
              NPM_VERSION: ${NPM_VERSION}

        ports:
            - '127.0.0.1:5000:5000'

        volumes:
            - ../../:/usr/user/workdir